### ISSUE TITLE
Install script fails on Arch Linux (unbound variable VERSION_ID)

### ISSUE THREAD

**Issue by StephenWeatherford** [dotnet/vscode-dotnet-runtime#11]
From https://github.com/microsoft/vscode-azurearmtools/issues/318:

> Downloading .NET Core tooling version(s) 2.2.5 ...... Error!
> Failed to download .NET Core tooling 2.2.5:
> /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 147: VERSION_ID: unbound variable
> /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 205: VERSION_ID: unbound variable
> /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 147: VERSION_ID: unbound variable
> /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 147: VERSION_ID: unbound variable

> Error: /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 147: VERSION_ID: unbound variable
> /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 205: VERSION_ID: unbound variable
> /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 147: VERSION_ID: unbound variable
> /home/ha/.vscode/extensions/msazurermtools.azurerm-vscode-tools-0.7.0/assets/install scripts/dotnet-install.sh: line 147: VERSION_ID: unbound variable

> If I run dotnet-install.sh, it works with the similar unbound VERSION_ID error. It installs sdk 2.1.802.
> I realized that the dotnet-install.sh script sources /etc/os-release to get VERSION_ID, but arch linux does not define that variable.
> $ cat /etc/os-release 
> NAME="Arch Linux"
> PRETTY_NAME="Arch Linux"
> ID=arch
> BUILD_ID=rolling
> ANSI_COLOR="0;36"
> HOME_URL="https://www.archlinux.org/"
> DOCUMENTATION_URL="https://wiki.archlinux.org/"
> SUPPORT_URL="https://bbs.archlinux.org/"
> BUG_REPORT_URL="https://bugs.archlinux.org/"
> LOGO=archlinux
> 
> I tried adding a line to /etc/os-release and it worked.
> VERSION_ID=0
> So, it looks like the issue needs to be filed for dotnet-install.sh.

**Comment by sfoslund** [comment]
Looking into this issue a bit, I believe it will be solved when the `vscode-azurearmtools` extension converts to using this extension for acquisition. The [install scripts in the repo](https://github.com/microsoft/vscode-azurearmtools/blob/master/assets/install%20scripts/dotnet-install.sh#L147) are out of date and don't have [a fix that was made for this issue](https://github.com/dotnet/toolset/pull/3481/commits/c9c42a0856a2a657cf93bda530aad1d3b532b96b#diff-3385102241bcd3718b9ca13a0c55b9afL147-R152). This shouldn't be an issue with this extension since we [dynamically acquire the most updated versions of the installation scripts](https://github.com/dotnet/vscode-dotnet-runtime/pull/23).

It looks like the original issue also had a separate bug with the error `Unexpected path returned for .net core` in which `dotnet.exe` did not exist. I've adapted [the arm tools solution](https://github.com/microsoft/vscode-azurearmtools/blob/master/src/acquisition/DotnetCoreAcquisitionWorker.ts#L220-L242) for detecting corrupted installations [here](https://github.com/dotnet/vscode-dotnet-runtime/blob/master/vscode-dotnet-runtime-library/src/Acquisition/InstallationValidator.ts), which should at least give a better error in this case. It might make sense to do more than throw an error here, i.e. try to reinstall the corrupted version. 

Let me know if I'm misunderstanding either of those bugs, but if not I think we're okay to close this (at least in this repo). @StephenWeatherford if you think it's worthwhile, I'll track the work for attempting to repair corrupted versions as a separate issue.

**Comment by StephenWeatherford** [comment]
Sounds good, thanks!
