### ISSUE TITLE
Question on use case

### ISSUE THREAD

**Issue by ron-myers** [dotnet/vscode-dotnet-runtime#111]
I am here to raise my hand as a beta tester.

First, I would like to clarify if, the intention of this project that it should be used as a `extensionDependencies` for when a VS Code extension requires that the dotnet runtime be available on a machine. Or only for extension development?

My use case:
* my extension interacts with a dotnet installed too - specifically (https://www.nuget.org/packages/UnderTest.FeatureLint)
* the extension calls a dotnet tool installed through `dotnet tool install`
* only need the runtime to be able to use those commands and have the runtime available.

Happy to clarify any portion of this if I am unclear.

**Comment by KathleenDollard** [comment]
I don't think the extension will help your scenario, but happy to talk this through and see if I am correct. 

Currently, the extension only installs the runtime and `dotnet tool install` is part of the SDK, not the runtime. Also, in order to manage uninstall via VS Code rules instead of platform specific installer rules, we use a different copy of the runtime in Code that is not easily available at the command line. 

So, regardless of whether the extension is installed, the user will have to separately install the .NET SDK for `dotnet tool install`.

**Comment by ron-myers** [comment]
Thank you @KathleenDollard.  That is very helpful.

My extension does require the SDK.  

Do you have any guidance on the best extension to install the SDK - I am currently using `ms-dotnettools.csharp`.

**Comment by sfoslund** [comment]
We don't currently have one unified extension for installing the SDK, this extension installs the runtime only. I'm going to close this issue, but please let us know if you have more questions, thanks!
