### ISSUE TITLE
VS Code, specifically C# Dev Kit, is not detecting the installed dotnet SDKs

### ISSUE THREAD

**Issue by S1rAardvark** [dotnet/vscode-dotnet-runtime#1239]
When starting VS Code, the error pops up that C# Dev Kit doesn't detect any installed SDKs, despite manually installing and reinstalling them several times. 
![image](https://github.com/dotnet/sdk/assets/64706386/9e9c5518-cbc5-4bf4-ae26-cb5653b83e4b)
Running dotnet --info gives me this:
![image](https://github.com/dotnet/sdk/assets/64706386/ecb3a0f6-1de4-4278-8f51-0014d93a4a3f)
I've checked several different other posts about it, and there's no alternate folder for dotnet in Program Files x86, which seemed to have been the main issue, so I'm unsure as to what I can do. The version of .NET SDK that I'm trying to use is the 4.7.1 Dev Pack, used for this, or it should be the version used for it.

**Comment by baronfel** [comment]
This is a know issue that we're working through with the C#/DevKit teams.  The version of this extension being used by C#/Dev Kit was intended for local-only installs of the SDk/Runtime in environments without elevated permissions,and so we designed around that.  You can work around the downloads by specifying a manual path to the dotnet install following [these instructions](https://github.com/dotnet/vscode-dotnet-runtime/blob/main/Documentation/troubleshooting-runtime.md).

In the near term, we're working with those teams to add existence checks for the SDK to their extensions (since the expected usage model they want and the model this extension provides are so drastically different), but we're also working on a v2 of this extension built for a tooling use case - managing shared, global installs of the SDK and Runtimes and allowing for existing SDKs/Runtimes on the host machine.

**Comment by archer884** [comment]
This garbage is still broken a year later, btw.

**Comment by Michal-MK** [comment]
Started happening to me on MacOS right now as well

**Comment by d-cantwell** [comment]
Still broken.  Also the link doesn't have linux instructions.  Why mark this as closed if it hasn't been fixed?

**Comment by spicybackend** [comment]
https://github.com/microsoft/vscode-dotnettools/issues/1732#issuecomment-2611362439

Installing the pre-release version of the C# Dev Kit extension and unchecking the legacy resolution setting worked for me after facing the this issue in WSL with dotnet installed via Homebrew.

**Comment by RG-404** [comment]
Still broken.

**Comment by WisperGatis** [comment]
Still broken
