### ISSUE TITLE
[NETE2ESDK] The SDK uninstalled through the control panel is still displayed in the list when running the ‘.NET Install Tool: Uninstall .NET’ command

### ISSUE THREAD

**Issue by v-xiaofchen** [dotnet/vscode-dotnet-runtime#1918]
### Describe the bug.

The SDK uninstalled through the control panel is still displayed in the list when running the ‘.NET Install Tool: Uninstall .NET’ command

### Reproduction Steps

1. Run the command ‘.NET Install Tool: Install .NET SDK System-Wide' to install the .NET SDK and enter the newest version. 
2. Uninstall the installed SDK through the control panel
3. Open the command palette and run the ‘.NET Install Tool: Uninstall.NET’ command
4. Observe

### Expected Behavior

The SDK uninstalled through the control panel should not appear in the list

### Exceptions & Errors (if any)

The SDK uninstalled through the control panel is still displayed in the list when running the ‘.NET Install Tool: Uninstall .NET’ command
![image](https://github.com/user-attachments/assets/d68fdc22-9e99-410a-aa07-dc3ef1d3f5cb)

### .NET Install Tool Version

2.1.2

### Your operating system? Please provide more detail, such as the version and or distro above.

N/A

### VS Code Version

1.92.2

**Comment by v-xiaofchen** [comment]
This issue also repro on MAC when manually uninstalling the SDK on using the script refer to this https://learn.microsoft.com/en-us/visualstudio/mac/uninstall-net-2022?view=vsmac-2022#uninstall-net-from-your-machine

**Comment by nagilson** [comment]
That's a good point. This is expected behavior but might cause confusion -- uninstalling it will should/(will be, based on my testing) a no-op where nothing happens, which is fine. The uninstallation feature is currently only for installations that were managed by the extension, it does not have knowledge of other installations.

This also means SDKs showing in the control panel will not appear here if they weren't installed via our tool.

cc @baronfel @webreidi  if you think we need to do anything about the messaging for this

**Comment by webreidi** [comment]
We'll need to make sure that documentation for this is clear that it will only list SDKs that were installed through VS Code. I can't think of any easy way to make that clear in the list itself. And the tool is only meant to provide a way to clean up what we initiated/enabled, so I don't think we need to provide access to remove all SDKs.

**Comment by nagilson** [comment]
Thank you, I agree.

**Comment by v-xiaofchen** [comment]
Thanks for your explanation！🙂

**Comment by v-xiaofchen** [comment]
Closed it as by design.
