### ISSUE TITLE
command path

### ISSUE THREAD

**Issue by Philsb9032** [dotnet/vscode-dotnet-runtime#214]
The issue text was copied to the clipboard.  Please paste it into this window.

Please attach the log file located at c:\Users\phils\AppData\Roaming\Code\logs\20210418T095804\exthost5\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1618737460150.txt. Note that this file may contain personal data.

Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

**Comment by khashayarnazari** [comment]
Sent from my BlackBerry 10 smartphone.                                                                                                                                                                                                                From: Philsb9032Sent: یکشنبه ۱۸ آوریل ۲۰۲۱،‏ ۱۳:۴۸To: dotnet/vscode-dotnet-runtimeReply To: dotnet/vscode-dotnet-runtimeCc: SubscribedSubject: [dotnet/vscode-dotnet-runtime] command path (#214)
The issue text was copied to the clipboard.  Please paste it into this window.
Please attach the log file located at c:\Users\phils\AppData\Roaming\Code\logs\20210418T095804\exthost5\ms-dotnettools.vscode-dotnet-runtime\DotNetAcquisition1618737460150.txt. Note that this file may contain personal data.
Privacy Alert! The contents copied to your clipboard may contain personal data. Prior to posting to GitHub, please remove any personal data which should not be publicly viewable. https://privacy.microsoft.com/en-US/privacystatement

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/dotnet/vscode-dotnet-runtime/issues/214",
"url": "https://github.com/dotnet/vscode-dotnet-runtime/issues/214",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by sfoslund** [comment]
Hi @Philsb9032, thanks for filing an issue. I'm going to close this for now as there is not enough information to be actionable, but please reopen with more information on what the error is. You can do this by pasting in the information copied to your clipboard when you made this issue and attaching the log file listed in the issue body. Thanks!
